# Generated by Django 4.2.5 on 2023-12-09 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientquiz_quiz_id', models.IntegerField()),
                ('clientquiz_host_id', models.CharField(max_length=200)),
                ('clientquiz_start_time', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('clientquiz_end_time', models.DateTimeField()),
                ('clientquiz_time_taken', models.DurationField()),
                ('clientquiz_total_questions', models.IntegerField()),
                ('clientquiz_attempted_questions', models.IntegerField()),
                ('clientquiz_correct_answers', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='ClientQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientquestion_question_id', models.IntegerField()),
                ('clientquiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientquiz')),
            ],
        ),
        migrations.CreateModel(
            name='ClientChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientchoice_choice_id', models.IntegerField()),
                ('is_correct_choice', models.BooleanField(default=False)),
                ('clientquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientquestion')),
            ],
        ),
    ]
