# Generated by Django 4.2.5 on 2023-12-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.TextField(unique=True, verbose_name='UID')),
                ('user_username', models.CharField(default=None, max_length=200, null=True, verbose_name='Username')),
                ('user_name', models.CharField(max_length=200, verbose_name='Name')),
                ('user_email', models.CharField(max_length=200, verbose_name='Email')),
                ('user_pfp', models.TextField()),
                ('user_quizzes_hosted', models.IntegerField(default=0)),
                ('user_quizzes_joined', models.IntegerField(default=0)),
            ],
        ),
    ]
