# Generated by Django 4.2.5 on 2023-12-09 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField()),
                ('quiz_host_id', models.CharField(max_length=200)),
                ('quiz_title', models.TextField()),
                ('quiz_timer_minutes', models.IntegerField()),
                ('quiz_publish_date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('quiz_start_date', models.DateTimeField(default=None, null=True)),
                ('quiz_is_held', models.BooleanField(default=False)),
                ('quiz_visible', models.BooleanField(default=True)),
                ('quiz_no_of_users', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_text', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.IntegerField()),
                ('choice_text', models.TextField()),
                ('is_correct_choice', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.question')),
            ],
        ),
    ]
